-- ============================================================
-- SAMPLE DATA FOR SIDDHIVINAYAK OVERSEAS
-- ============================================================

-- Countries
INSERT INTO countries (code, name, slug, capital, region, subregion, latitude, longitude, currency, currency_code, language, flag_emoji, description, why_study, why_work, lifestyle, cost_of_living, climate, visa_stats, sort_order, meta_title, meta_desc) VALUES
('JPN', 'Japan', 'japan', 'Tokyo', 'Asia', 'Eastern Asia', 36.2048, 138.2529, 'Japanese Yen', 'JPY', 'Japanese', '🇯🇵', 
'Japan offers world-class work opportunities in technology, engineering, and manufacturing. With a unique blend of tradition and cutting-edge innovation, Japan is a top destination for skilled professionals.',
'Japan has over 700 universities, many ranked globally. The MEXT scholarship program and post-study work visas make it highly attractive for international students.',
'Japan offers the Specified Skilled Worker visa for 14 sectors including IT, nursing, agriculture, and construction. Strong worker protections and competitive salaries.',
'Safe, clean, efficient public transport, world-class cuisine, and a unique culture that blends ancient traditions with futuristic technology.',
'{"monthly_single": 120000, "monthly_family": 220000, "rent_studio_inr": 75000, "transport_monthly_inr": 8000, "groceries_monthly_inr": 25000}',
'{"type": "temperate", "summers": "warm and humid", "winters": "cold with snow in north", "best_time": "March-May, Oct-Nov"}',
'{"success_rate": 94.5, "avg_processing_days": 45, "popular_sectors": ["IT", "Engineering", "Healthcare", "Agriculture"]}',
1,
'Japan Work & Study Visa | Siddhivinayak Overseas',
'Apply for Japan work visa and study visa with expert guidance. Specified Skilled Worker program, student visas, and permanent residency pathways.'),

('AUS', 'Australia', 'australia', 'Canberra', 'Oceania', 'Australia and New Zealand', -25.2744, 133.7751, 'Australian Dollar', 'AUD', 'English', '🇦🇺',
'Australia offers an excellent quality of life, high wages, and a welcoming environment for skilled migrants. The points-based system rewards qualified professionals.',
'Australia has 43 universities, with many in the world top 100. The post-study work visa allows graduates to stay 2-4 years after completion.',
'The Subclass 482 (Temporary Skill Shortage) and Subclass 186 (Employer Nomination) visas are popular. Strong demand in healthcare, IT, engineering, and trades.',
'Outdoor lifestyle, multicultural cities, beautiful beaches, and a relaxed work culture. Excellent work-life balance and social services.',
'{"monthly_single": 180000, "monthly_family": 320000, "rent_studio_inr": 120000, "transport_monthly_inr": 10000, "groceries_monthly_inr": 35000}',
'{"type": "varied", "summers": "hot and dry in south, wet in north", "winters": "mild", "best_time": "Sep-Nov, Mar-May"}',
'{"success_rate": 91.2, "avg_processing_days": 60, "popular_sectors": ["Healthcare", "IT", "Engineering", "Construction", "Education"]}',
2,
'Australia Work & Study Visa | Siddhivinayak Overseas',
'Australia skilled migration, student visas, and PR pathways. Expert consultants for 482 TSS visa, 186 ENS visa, and post-study work permits.'),

('CAN', 'Canada', 'canada', 'Ottawa', 'Americas', 'Northern America', 56.1304, -106.3468, 'Canadian Dollar', 'CAD', 'English, French', '🇨🇦',
'Canada is one of the most immigration-friendly countries with clear pathways to permanent residency. It actively seeks skilled workers through Express Entry and PNPs.',
'Canadian universities are globally recognized and more affordable than US counterparts. The PGWP allows graduates to work for up to 3 years after studies.',
'Express Entry (FSW, CEC, FST), Provincial Nominee Programs, and the Atlantic Immigration Program are major pathways. Canada plans to welcome 500,000 immigrants annually by 2025.',
'Safe, inclusive, multicultural society with universal healthcare, beautiful natural scenery, and vibrant cities. High standard of living.',
'{"monthly_single": 150000, "monthly_family": 280000, "rent_studio_inr": 90000, "transport_monthly_inr": 7000, "groceries_monthly_inr": 30000}',
'{"type": "continental", "summers": "warm", "winters": "very cold", "best_time": "May-Sep"}',
'{"success_rate": 92.8, "avg_processing_days": 90, "popular_sectors": ["IT", "Healthcare", "Finance", "Engineering", "Trades"]}',
3,
'Canada Work & Study Visa | Express Entry | Siddhivinayak Overseas',
'Canada Express Entry, Provincial Nominee Programs, study permits, and PGWP. Expert guidance for PR pathways and LMIA work permits.'),

('GBR', 'United Kingdom', 'united-kingdom', 'London', 'Europe', 'Northern Europe', 55.3781, -3.4360, 'British Pound', 'GBP', 'English', '🇬🇧',
'The UK offers the Skilled Worker visa and Graduate visa for international talent. London is a global hub for finance, tech, and creative industries.',
'UK universities rank among the worlds best. The Graduate Route allows 2 years of post-study work (3 years for PhD). Shorter degree programs save time and money.',
'The Skilled Worker visa replaced the Tier 2 visa. It requires a job offer from a licensed sponsor. The Health and Care Worker visa offers fast-track processing.',
'Rich history, cultural diversity, world-class arts and entertainment, and excellent travel connections to Europe. Strong workers rights.',
'{"monthly_single": 200000, "monthly_family": 350000, "rent_studio_inr": 130000, "transport_monthly_inr": 12000, "groceries_monthly_inr": 30000}',
'{"type": "maritime", "summers": "mild and sometimes wet", "winters": "cold and damp", "best_time": "Jun-Aug"}',
'{"success_rate": 89.5, "avg_processing_days": 30, "popular_sectors": ["Healthcare", "Finance", "IT", "Engineering", "Education"]}',
4,
'UK Work Visa & Study Visa | Skilled Worker | Siddhivinayak Overseas',
'UK Skilled Worker visa, Health and Care visa, Graduate Route, and student visas. Expert guidance for sponsors and NHS pathways.'),

('DEU', 'Germany', 'germany', 'Berlin', 'Europe', 'Western Europe', 51.1657, 10.4515, 'Euro', 'EUR', 'German', '🇩🇪',
'Germany has Europes strongest economy and a severe skilled worker shortage. The new Opportunity Card (Chancenkarte) makes job searching easier than ever.',
'German public universities charge little to no tuition. Strong programs in engineering, automotive, and research. The 18-month post-study work visa is generous.',
'The EU Blue Card, Skilled Immigration Act, and new Opportunity Card offer multiple pathways. High demand in IT, engineering, healthcare, and skilled trades.',
'Excellent public transport, work-life balance, strong social safety net, and central European location for travel. Rich cultural heritage.',
'{"monthly_single": 140000, "monthly_family": 260000, "rent_studio_inr": 85000, "transport_monthly_inr": 8000, "groceries_monthly_inr": 28000}',
'{"type": "temperate", "summers": "warm", "winters": "cold", "best_time": "May-Sep"}',
'{"success_rate": 93.1, "avg_processing_days": 50, "popular_sectors": ["Engineering", "IT", "Healthcare", "Automotive", "Manufacturing"]}',
5,
'Germany Work & Study Visa | EU Blue Card | Siddhivinayak Overseas',
'Germany Opportunity Card, EU Blue Card, skilled worker visa, and study permits. Free education and strong job market for skilled professionals.'),

('NZL', 'New Zealand', 'new-zealand', 'Wellington', 'Oceania', 'Australia and New Zealand', -40.9006, 174.8860, 'New Zealand Dollar', 'NZD', 'English, Maori', '🇳🇿',
'New Zealand offers a high quality of life, stunning landscapes, and a straightforward points-based immigration system. It actively seeks skilled migrants.',
'NZ universities offer practical, industry-aligned programs. The post-study work visa allows up to 3 years depending on qualification level.',
'The Skilled Migrant Category (SMC) and Accredited Employer Work Visa (AEWV) are primary pathways. Strong demand in healthcare, IT, construction, and agriculture.',
'World-famous natural beauty, outdoor adventure culture, friendly communities, and excellent work-life balance. Safe and stable society.',
'{"monthly_single": 130000, "monthly_family": 240000, "rent_studio_inr": 80000, "transport_monthly_inr": 7000, "groceries_monthly_inr": 26000}',
'{"type": "maritime", "summers": "warm", "winters": "mild", "best_time": "Dec-Feb"}',
'{"success_rate": 88.7, "avg_processing_days": 75, "popular_sectors": ["Healthcare", "IT", "Construction", "Agriculture", "Education"]}',
6,
'New Zealand Work & Study Visa | Skilled Migrant | Siddhivinayak Overseas',
'New Zealand Skilled Migrant Category, Accredited Employer Work Visa, and study pathways. Expert guidance for NZ immigration points system.'),

('RUS', 'Russia', 'russia', 'Moscow', 'Europe', 'Eastern Europe', 61.5240, 105.3188, 'Russian Ruble', 'RUB', 'Russian', '🇷🇺',
'Russia offers opportunities in engineering, energy, and technology sectors. Work visas are employer-sponsored with straightforward requirements.',
'Russia has a strong tradition in STEM education. Affordable tuition fees and generous scholarships for international students.',
'Work permits are employer-sponsored. Strong demand in oil & gas, IT, engineering, and construction sectors.',
'Vast and diverse country with rich cultural heritage, world-class arts, and unique urban experiences. Low cost of living.',
'{"monthly_single": 80000, "monthly_family": 150000, "rent_studio_inr": 45000, "transport_monthly_inr": 4000, "groceries_monthly_inr": 18000}',
'{"type": "continental", "summers": "warm", "winters": "very cold", "best_time": "May-Sep"}',
'{"success_rate": 85.3, "avg_processing_days": 40, "popular_sectors": ["Energy", "Engineering", "IT", "Construction", "Manufacturing"]}',
7,
'Russia Work & Study Visa | Siddhivinayak Overseas',
'Russia work permits and student visas. Opportunities in energy, engineering, and technology sectors with affordable living costs.'),

('USA', 'United States', 'united-states', 'Washington D.C.', 'Americas', 'Northern America', 37.0902, -95.7129, 'US Dollar', 'USD', 'English', '🇺🇸',
'The USA remains the top destination for skilled professionals and students. The H-1B, L-1, and O-1 visas offer pathways for talent across industries.',
'Home to 8 of the worlds top 10 universities. Optional Practical Training (OPT) allows 12-36 months of work after graduation.',
'H-1B specialty occupation visas, L-1 intracompany transfers, O-1 extraordinary ability, and EB green cards. The Diversity Visa Lottery offers 50,000 slots annually.',
'Diverse culture, entrepreneurial ecosystem, top-tier entertainment, and unparalleled career growth opportunities in tech, finance, and entertainment hubs.',
'{"monthly_single": 250000, "monthly_family": 450000, "rent_studio_inr": 150000, "transport_monthly_inr": 15000, "groceries_monthly_inr": 40000}',
'{"type": "varied", "summers": "hot in south, mild in north", "winters": "cold in north, mild in south", "best_time": "Mar-May, Sep-Nov"}',
'{"success_rate": 87.4, "avg_processing_days": 120, "popular_sectors": ["IT", "Healthcare", "Finance", "Engineering", "Research"]}',
8,
'USA Work Visa & Study Visa | H-1B, F-1, OPT | Siddhivinayak Overseas',
'USA H-1B visa, F-1 student visa, OPT, L-1 transfer, and O-1 extraordinary ability visas. Expert guidance for US immigration.'),

('IND', 'India', 'india', 'New Delhi', 'Asia', 'Southern Asia', 20.5937, 78.9629, 'Indian Rupee', 'INR', 'Hindi, English', '🇮🇳',
'India is a top source country for skilled migrants worldwide. We help Indian professionals and students achieve their overseas dreams.',
'India produces millions of graduates annually. We guide students to the best international universities matching their profiles.',
'We help Indian skilled workers navigate visa requirements for all major destination countries, with documentation and interview preparation.',
'Rich cultural diversity, strong family values, and a growing professional class seeking global opportunities.',
'{"monthly_single": 40000, "monthly_family": 80000, "rent_studio_inr": 20000, "transport_monthly_inr": 3000, "groceries_monthly_inr": 12000}',
'{"type": "tropical to temperate", "summers": "hot", "winters": "mild", "best_time": "Oct-Mar"}',
'{"success_rate": 96.0, "avg_processing_days": 30, "popular_sectors": ["IT", "Healthcare", "Engineering", "Finance", "Education"]}',
9,
'India Best Visa Consultants | Work & Study Abroad | Siddhivinayak Overseas',
'Indias trusted visa consultancy for work and study visas to Japan, Australia, Canada, UK, Germany, New Zealand, Russia, and USA.'),

('ARE', 'United Arab Emirates', 'united-arab-emirates', 'Abu Dhabi', 'Asia', 'Western Asia', 23.4241, 53.8478, 'UAE Dirham', 'AED', 'Arabic, English', '🇦🇪',
'The UAE offers tax-free salaries, modern infrastructure, and a cosmopolitan lifestyle. The Golden Visa provides long-term residency for skilled professionals.',
'Dubai and Abu Dhabi host branches of top international universities. Student visa process is straightforward and quick.',
'The UAE Employment Visa and Golden Visa (10-year residency) attract talent from across the globe. Zero income tax is a major draw.',
'Ultramodern cities, luxury lifestyle, diverse expat community, and strategic location between East and West.',
'{"monthly_single": 180000, "monthly_family": 320000, "rent_studio_inr": 110000, "transport_monthly_inr": 8000, "groceries_monthly_inr": 30000}',
'{"type": "desert", "summers": "extremely hot", "winters": "warm and pleasant", "best_time": "Nov-Mar"}',
'{"success_rate": 95.2, "avg_processing_days": 20, "popular_sectors": ["Finance", "IT", "Hospitality", "Construction", "Aviation"]}',
10,
'UAE Work Visa & Golden Visa | Siddhivinayak Overseas',
'UAE employment visa, Golden Visa, and student permits. Tax-free income and long-term residency options for skilled professionals.');

-- Visa Programs
INSERT INTO visa_programs (country_id, program_type, name, slug, description, eligibility, requirements, documents_needed, processing_time, visa_duration, cost_inr, cost_local, cost_currency, success_rate, pathway_to_pr, spousal_rights, work_while_study, post_study_work, popular_sectors, universities, is_featured, sort_order, meta_title, meta_desc) VALUES
-- Japan Programs
((SELECT id FROM countries WHERE code='JPN'), 'work', 'Specified Skilled Worker Visa (SSW)', 'specified-skilled-worker',
'The Specified Skilled Worker visa allows employment in 14 sectors facing labor shortages. It offers a pathway to permanent residency and can bring family after certain conditions.',
'["Age 18+", "Passed required skills test", "Passed Japanese language test (N4 or above)", "Job offer from registered employer", "Clean criminal record"]',
'["Valid passport", "Employment contract", "Skills test certificate", "Japanese language certificate", "Health check"]',
'["Passport (6+ months validity)", "Visa application form", "Photo (45x45mm)", "Certificate of Eligibility (COE)", "Employment contract", "Skills test results", "Japanese language test results"]',
'2-3 months (after COE)', '1 year, renewable up to 5 years', 85000, 135000, 'JPY', 94.5, true, true, false, 'Not applicable for work visa',
'["Caregiving", "Building cleaning", "Agriculture", "Fishery", "Food service", "Accommodation", "Automotive repair", "Aviation", "Shipbuilding", "Industrial machinery", "Electronics", "Construction", "Material processing", "Nursing"]',
'[]', true, 1,
'Japan Specified Skilled Worker Visa | SSW Visa Requirements',
'Apply for Japans Specified Skilled Worker visa. 14 sectors available, pathway to PR, family sponsorship. Expert guidance for skills and language tests.'),

((SELECT id FROM countries WHERE code='JPN'), 'study', 'Student Visa (College/University)', 'student-visa',
'Japan offers world-class education in technology, medicine, and humanities. The student visa allows part-time work (28 hours/week) and post-graduation employment options.',
'["Age 18+", "High school diploma or equivalent", "Japanese language proficiency (N5 minimum, N2 recommended)", "Proof of financial support (1.5M JPY/year)", "Acceptance letter from institution"]',
'["Valid passport", "Admission letter", "Financial proof", "Language certificate", "Academic transcripts", "Health certificate"]',
'["Passport", "Visa application form", "Photo", "Certificate of Eligibility (COE)", "Admission letter", "Financial documents", "Academic records", "Language certificate", "Statement of purpose"]',
'1-2 months (after COE)', 'Duration of course + 3 months', 65000, 100000, 'JPY', 96.2, false, false, true, 'Up to 1 year (depends on degree)',
'["Engineering", "Medicine", "Business", "IT", "Japanese Language"]',
'["University of Tokyo", "Kyoto University", "Osaka University", "Tohoku University", "Tokyo Institute of Technology", "Waseda University", "Keio University"]',
true, 2,
'Japan Student Visa | Study in Japan | Siddhivinayak Overseas',
'Japan student visa application guidance. Part-time work allowed, post-study employment options, MEXT scholarships. Top university admissions support.'),

-- Australia Programs
((SELECT id FROM countries WHERE code='AUS'), 'work', 'Temporary Skill Shortage Visa (Subclass 482)', 'temporary-skill-shortage-482',
'The TSS 482 visa allows skilled workers to live and work in Australia for an approved employer. It offers a pathway to permanent residency through the Temporary Residence Transition stream.',
'["Occupation on eligible list", "2+ years relevant work experience", "Skills assessment (if required)", "English proficiency (IELTS 5.0+)", "Employer sponsorship from approved business"]',
'["Valid passport", "Skills assessment", "English test results", "Employment references", "Health insurance (OVHC)", "Police clearances"]',
'["Passport", "Application form", "Skills assessment", "Employment contracts", "Reference letters", "English test", "Health examination", "Police certificates", "Health insurance proof"]',
'1-3 months', 'Up to 4 years (2 years for short-term)', 150000, 3000, 'AUD', 91.2, true, true, false, 'PR pathway via TRT stream',
'["IT", "Engineering", "Healthcare", "Accounting", "Construction", "Education", "Hospitality", "Agriculture"]',
'[]', true, 1,
'Australia 482 TSS Visa | Temporary Skill Shortage | Siddhivinayak Overseas',
'Australia 482 visa application. Employer sponsorship, skills assessment, and PR pathway. Expert guidance for skilled worker migration.'),

((SELECT id FROM countries WHERE code='AUS'), 'study', 'Student Visa (Subclass 500)', 'student-visa-500',
'The Student Visa 500 allows international students to study full-time at Australian institutions. Includes work rights and post-study work visa options.',
'["Enrollment in CRICOS-registered course", "Genuine Temporary Entrant (GTE) requirement", "English proficiency (IELTS 5.5+)", "Financial capacity (tuition + living costs)", "Overseas Student Health Cover (OSHC)"]',
'["Valid passport", "COE (Confirmation of Enrollment)", "GTE statement", "English test", "Financial documents", "Health insurance (OSHC)", "Health examination"]',
'["Passport", "Application form", "COE", "GTE statement", "Academic transcripts", "English test results", "Financial evidence", "OSHC certificate", "Health check", "Police clearances"]',
'1-3 months', 'Duration of course', 120000, 1600, 'AUD', 93.8, false, false, true, '2-4 years via Temporary Graduate Visa (485)',
'["Business", "Engineering", "IT", "Healthcare", "Education", "Hospitality"]',
'["University of Melbourne", "Australian National University", "University of Sydney", "UNSW", "Monash University", "University of Queensland"]',
true, 2,
'Australia Student Visa 500 | Study in Australia | Siddhivinayak Overseas',
'Australia student visa Subclass 500. CRICOS courses, GTE guidance, OSHC, and post-study work visa pathway. Top university admissions support.'),

((SELECT id FROM countries WHERE code='AUS'), 'work', 'Skilled Independent Visa (Subclass 189)', 'skilled-independent-189',
'The Subclass 189 is a points-based permanent residency visa for skilled workers who are not sponsored by an employer, family member, or state/territory.',
'["Occupation on MLTSSL", "Positive skills assessment", "Age under 45", "Competent English (IELTS 6.0+)", "Score minimum 65 points on points test"]',
'["Skills assessment", "English test", "Age proof", "Work experience evidence", "Educational qualifications", "Partner skills (if applicable)"]',
'["Passport", "Skills assessment", "English test", "Employment references", "Academic documents", "Partner documents (if applicable)", "Health examination", "Police clearances"]',
'8-12 months', 'Permanent', 250000, 4240, 'AUD', 88.5, true, true, false, 'Permanent visa - PR from day one',
'["IT", "Engineering", "Healthcare", "Accounting", "Education", "Trades"]',
'[]', true, 3,
'Australia 189 PR Visa | Skilled Independent | Siddhivinayak Overseas',
'Australia permanent residency via Skilled Independent 189 visa. Points test optimization, skills assessment, and EOI submission guidance.'),

-- Canada Programs
((SELECT id FROM countries WHERE code='CAN'), 'work', 'Express Entry - Federal Skilled Worker', 'express-entry-fsw',
'Express Entry is Canadas primary system for managing skilled worker applications. The Federal Skilled Worker program is for professionals with foreign work experience.',
'["1+ year continuous skilled work experience", "Canadian Language Benchmark 7+", "Educational Credential Assessment", "Sufficient settlement funds", "Score competitive CRS points"]',
'["Passport", "Language test (IELTS/CELPIP/TEF)", "ECA report", "Work reference letters", "Police certificates", "Medical exam", "Proof of funds"]',
'["Passport", "Photos", "Language test results", "ECA", "Work experience letters", "Police clearances", "Medical exam results", "Bank statements", "Employment records"]',
'6-8 months (after ITA)', 'Permanent', 180000, 1365, 'CAD', 92.8, true, true, false, 'Permanent visa - PR from day one',
'["IT", "Engineering", "Finance", "Healthcare", "Marketing", "Accounting", "Education"]',
'[]', true, 1,
'Canada Express Entry | Federal Skilled Worker | Siddhivinayak Overseas',
'Canada Express Entry profile creation, CRS score optimization, and ITA application. Federal Skilled Worker, CEC, and FST pathways to PR.'),

((SELECT id FROM countries WHERE code='CAN'), 'study', 'Study Permit', 'study-permit',
'The Canadian study permit allows international students to study at Designated Learning Institutions (DLIs). Includes work rights and a clear PGWP pathway.',
'["Acceptance letter from DLI", "Proof of financial support", "Clean criminal record", "Medical exam (if required)", "Genuine intent to leave Canada after studies (initially)"]',
'["Valid passport", "DLI acceptance letter", "Proof of funds", "Quebec Acceptance Certificate (CAQ) if applicable", "Medical exam", "Statement of purpose"]',
'["Passport", "Application form", "DLI letter", "Financial proof", "SOP", "CAQ (if Quebec)", "Medical exam", "Police certificate", "Biometrics", "Family information"]',
'2-4 months', 'Duration of course + 90 days', 100000, 150, 'CAD', 94.1, false, false, true, 'Up to 3 years via PGWP',
'["Computer Science", "Engineering", "Business", "Healthcare", "Data Science", "Environmental Science"]',
'["University of Toronto", "McGill University", "UBC", "University of Waterloo", "University of Alberta", "McMaster University"]',
true, 2,
'Canada Study Permit | Student Visa | Siddhivinayak Overseas',
'Canada study permit for Designated Learning Institutions. PGWP pathway, work while study, and PR through Canadian Experience Class.'),

-- UK Programs
((SELECT id FROM countries WHERE code='GBR'), 'work', 'Skilled Worker Visa', 'skilled-worker',
'The UK Skilled Worker visa allows you to come to or stay in the UK to do an eligible job with an approved employer. It replaced the Tier 2 (General) visa.',
'["Job offer from licensed sponsor", "Job at appropriate skill level (RQF 3+)", "Minimum salary threshold (generally £26,200 or going rate)", "English proficiency (CEFR B1)", "Certificate of Sponsorship (CoS)"]',
'["Valid passport", "Certificate of Sponsorship", "Job title and annual salary", "Employer name and sponsor license number", "English language proof", "Personal savings proof", "Tuberculosis test (if applicable)"]',
'["Passport", "CoS reference number", "Proof of English knowledge", "Bank statements", "Tuberculosis test results", "Criminal record certificate (if applicable)", "Academic qualifications", "Employment contract"]',
'3-8 weeks', 'Up to 5 years', 120000, 719, 'GBP', 89.5, true, true, false, 'After 5 years, eligible for ILR',
'["Healthcare", "IT", "Engineering", "Finance", "Education", "Science", "Creative", "Agriculture"]',
'[]', true, 1,
'UK Skilled Worker Visa | Tier 2 Replacement | Siddhivinayak Overseas',
'UK Skilled Worker visa application. Licensed sponsor jobs, Certificate of Sponsorship, and ILR pathway. NHS and care worker fast-track available.'),

((SELECT id FROM countries WHERE code='GBR'), 'study', 'Student Visa', 'student-visa',
'The UK Student visa allows international students to study at licensed institutions. The Graduate Route provides 2 years of post-study work (3 years for PhD).',
'["Offer from licensed student sponsor", "English proficiency (CEFR B2 for degree level)", "Financial capacity (tuition + living costs)", "ATAS certificate (if required)", "Parental consent (if under 18)"]',
'["Valid passport", "CAS (Confirmation of Acceptance for Studies)", "Financial proof", "English test", "ATAS (if applicable)", "Tuberculosis test (if applicable)", "Parental consent (if under 18)"]',
'["Passport", "CAS", "Financial evidence", "English test", "Academic qualifications", "ATAS certificate", "Tuberculosis test", "Parental consent letter"]',
'3 weeks (priority available)', 'Duration of course + wrap-up', 90000, 490, 'GBP', 91.3, false, false, true, '2 years (3 years for PhD) via Graduate Route',
'["Business", "Law", "Engineering", "Medicine", "Computer Science", "Arts", "Social Sciences"]',
'["Oxford", "Cambridge", "Imperial College London", "UCL", "LSE", "University of Edinburgh"]',
true, 2,
'UK Student Visa | Graduate Route | Study in UK | Siddhivinayak Overseas',
'UK student visa and Graduate Route application. Russell Group admissions, CAS guidance, and 2-year post-study work visa support.'),

-- Germany Programs
((SELECT id FROM countries WHERE code='DEU'), 'work', 'Opportunity Card (Chancenkarte)', 'opportunity-card',
'The new Opportunity Card (Chancenkarte) allows skilled workers to come to Germany for up to 1 year to search for employment. No job offer required at application time.',
'["2+ years vocational training or university degree", "Basic German (A1) or English (B2)", "Proof of sufficient funds", "Maximum 6 points on points system (age, experience, language, etc.)"]',
'["Recognized qualification", "Language certificate", "Financial proof", "Health insurance", "CV and work references"]',
'["Passport", "Application form", "Photos", "Qualification documents", "Language certificate", "Financial proof", "Health insurance", "CV", "Work references", "Recognition of qualifications (if available)"]',
'4-12 weeks', '1 year (job search)', 95000, 75, 'EUR', 93.1, true, false, false, 'After finding job, switch to work permit or EU Blue Card',
'["Engineering", "IT", "Healthcare", "Skilled Trades", "Mathematics", "Natural Sciences"]',
'[]', true, 1,
'Germany Opportunity Card | Chancenkarte | Siddhivinayak Overseas',
'Germany new Opportunity Card for job seekers. Points-based system, no job offer needed. Pathway to EU Blue Card and permanent residency.'),

((SELECT id FROM countries WHERE code='DEU'), 'work', 'EU Blue Card', 'eu-blue-card',
'The EU Blue Card is for highly qualified non-EU professionals. It offers fast-track to permanent residency and favorable conditions for family reunification.',
'["University degree recognized in Germany", "Job offer with minimum salary threshold (€45,300+ or €41,041 for shortage occupations)", "Job relevant to qualification"]',
'["Valid passport", "University degree", "Employment contract", "Salary proof", "Health insurance", "German residence address (if applicable)"]',
'["Passport", "Application form", "Photos", "Degree with recognition", "Employment contract", "Salary statement", "Health insurance", "Housing proof"]',
'6-12 weeks', '4 years', 110000, 140, 'EUR', 95.4, true, true, false, 'After 27 months (with B1 German) or 21 months (with B1 and fast-track)',
'["IT", "Engineering", "Mathematics", "Natural Sciences", "Medicine", "Academic Research"]',
'[]', true, 2,
'Germany EU Blue Card | Highly Qualified Worker | Siddhivinayak Overseas',
'Germany EU Blue Card for highly qualified professionals. Fast-track PR, family reunification, and EU mobility rights.'),

((SELECT id FROM countries WHERE code='DEU'), 'study', 'Student Visa', 'student-visa',
'German public universities charge little to no tuition fees. The student visa allows part-time work (120 full days or 240 half days per year) and an 18-month job search period after graduation.',
'["University admission (conditional or unconditional)", "Proof of financial means (blocked account with €11,208/year)", "Health insurance", "Educational certificates recognized", "German or English proficiency (depending on program)"]',
'["Valid passport", "Admission letter", "Blocked account statement", "Health insurance", "Language certificate", "Academic transcripts", "Motivation letter"]',
'["Passport", "Application form", "Photos", "Admission letter", "Blocked account proof", "Health insurance", "Language certificate", "Academic documents", "CV", "Motivation letter"]',
'6-12 weeks', 'Duration of studies', 80000, 75, 'EUR', 96.7, false, false, true, '18 months after graduation',
'["Engineering", "Medicine", "Natural Sciences", "Computer Science", "Business", "Arts", "Social Sciences"]',
'["Technical University of Munich", "RWTH Aachen", "Karlsruhe Institute of Technology", "Humboldt University Berlin", "Free University of Berlin", "Heidelberg University"]',
true, 3,
'Germany Student Visa | Free Education | Study in Germany | Siddhivinayak Overseas',
'Germany student visa with zero tuition fees. Blocked account guidance, university admissions, and 18-month post-study job search visa.'),

-- NZ Programs
((SELECT id FROM countries WHERE code='NZL'), 'work', 'Accredited Employer Work Visa (AEWV)', 'accredited-employer-work-visa',
'The AEWV allows you to work for an accredited New Zealand employer. It replaced several previous work visa categories and streamlines employer sponsorship.',
'["Job offer from accredited employer", "Job pays at least median wage", "Employer has Job Check approval", "Relevant qualifications or experience", "Good health and character"]',
'["Valid passport", "Employment agreement", "Employer accreditation proof", "Job Check approval", "Qualifications/experience evidence", "Health and character documents"]',
'["Passport", "Application form", "Photos", "Employment contract", "Employer documents", "Qualification certificates", "Work references", "Health examination", "Police certificates"]',
'1-2 months', 'Up to 3 years (up to 5 for high-paid roles)', 130000, 495, 'NZD', 88.7, true, true, false, 'After 2 years on AEWV, eligible for residence via Work to Residence',
'["Healthcare", "IT", "Construction", "Engineering", "Agriculture", "Education", "Hospitality", "Manufacturing"]',
'[]', true, 1,
'New Zealand AEWV | Accredited Employer Work Visa | Siddhivinayak Overseas',
'New Zealand Accredited Employer Work Visa. Job Check requirements, median wage rules, and Work to Residence pathway.'),

((SELECT id FROM countries WHERE code='NZL'), 'study', 'Student Visa', 'student-visa',
'New Zealand offers quality education with practical focus. The student visa allows part-time work and a generous post-study work visa depending on qualification level.',
'["Offer of place from approved provider", "Paid tuition fees or evidence of funding", "Living cost proof (NZ$20,000/year)", "Genuine intent to study", "Good health and character"]',
'["Valid passport", "Offer letter", "Fee payment/receipt", "Financial documents", "Health insurance", "English test (if required)", "Academic transcripts", "Statement of purpose"]',
'["Passport", "Application form", "Photos", "Offer of place", "Fee receipt", "Financial evidence", "Health insurance", "English test", "Academic records", "SOP", "Health check", "Police certificates"]',
'1-2 months', 'Duration of course', 95000, 375, 'NZD', 92.4, false, false, true, '1-3 years depending on qualification level',
'["Business", "Engineering", "IT", "Hospitality", "Health Sciences", "Agriculture", "Creative Arts"]',
'["University of Auckland", "University of Otago", "Victoria University of Wellington", "University of Canterbury", "Massey University", "AUT"]',
true, 2,
'New Zealand Student Visa | Study in NZ | Siddhivinayak Overseas',
'New Zealand student visa application. Approved education providers, work rights, and post-study work visa for 1-3 years.'),

-- USA Programs
((SELECT id FROM countries WHERE code='USA'), 'work', 'H-1B Specialty Occupation Visa', 'h1b-visa',
'The H-1B visa allows US companies to employ graduate-level workers in specialty occupations requiring theoretical or technical expertise.',
'["Bachelors degree or higher in related field", "Job offer in specialty occupation", "Employer willing to sponsor", "Labor Condition Application (LCA) approved", "Annual cap applies (85,000 per year)"]',
'["Valid passport", "Degree certificates", "Employment offer letter", "LCA approval", "Resume/CV", "Work experience letters", "License (if occupation requires)"]',
'["Passport", "Form DS-160", "Photo", "LCA copy", "Employment letter", "Degree transcripts", "Resume", "Work references", "License documents"]',
'2-6 months (premium processing 15 days)', '3 years, extendable to 6', 200000, 460, 'USD', 82.5, true, true, false, 'Employer can sponsor EB green card',
'["IT", "Engineering", "Finance", "Accounting", "Architecture", "Science", "Medicine", "Education", "Law"]',
'[]', true, 1,
'USA H-1B Visa | Specialty Occupation | Siddhivinayak Overseas',
'USA H-1B visa application and lottery strategy. Specialty occupation requirements, LCA process, and employer sponsorship guidance.'),

((SELECT id FROM countries WHERE code='USA'), 'study', 'F-1 Student Visa', 'f1-student-visa',
'The F-1 visa is for academic students enrolled in US universities, colleges, high schools, or language training programs. Includes OPT work authorization.',
'["Acceptance by SEVP-certified school", "Full-time enrollment intent", "Sufficient financial support", "English proficiency or enrolled in English courses", "Non-immigrant intent (ties to home country)"]',
'["Valid passport", "Form I-20", "SEVIS fee payment", "Financial documents", "Academic transcripts", "English test (TOEFL/IELTS)", "Ties to home country evidence"]',
'["Passport", "Form DS-160", "Photo", "Form I-20", "SEVIS receipt", "Financial proof", "Academic documents", "English test", "SOP", "Bank statements", "Affidavit of support"]',
'2-4 weeks (varies by consulate)', 'Duration of program', 160000, 350, 'USD', 90.2, false, false, true, '12 months OPT (24 months STEM extension)',
'["Computer Science", "Engineering", "Business Administration", "Data Science", "Medicine", "Economics", "Psychology"]',
'["MIT", "Stanford", "Harvard", "Caltech", "University of Chicago", "University of Pennsylvania", "Columbia University"]',
true, 2,
'USA F-1 Student Visa | OPT | Study in USA | Siddhivinayak Overseas',
'USA F-1 student visa and OPT guidance. SEVIS, I-20, university admissions, and 12-36 month Optional Practical Training support.'),

-- UAE Programs
((SELECT id FROM countries WHERE code='ARE'), 'work', 'UAE Employment Visa', 'employment-visa',
'The UAE employment visa is sponsored by your employer. The process is streamlined and typically completed within 2-3 weeks once documents are ready.',
'["Valid job offer from UAE company", "Company holds valid trade license", "Applicant meets position requirements", "Medical fitness test", "Emirates ID registration"]',
'["Valid passport (6+ months)", "Degree attestation (if applicable)", "Medical fitness certificate", "Emirates ID application", "Health insurance", "Labor contract"]',
'["Passport copy", "Photos", "Degree certificates (attested)", "Medical test", "Emirates ID form", "Labor contract", "Company documents", "Insurance policy"]',
'2-4 weeks', '2-3 years (renewable)', 95000, 3000, 'AED', 95.2, false, true, false, 'Golden Visa available for exceptional talent',
'["Finance", "IT", "Hospitality", "Construction", "Healthcare", "Aviation", "Oil & Gas", "Real Estate"]',
'[]', true, 1,
'UAE Employment Visa | Work in Dubai/Abu Dhabi | Siddhivinayak Overseas',
'UAE employment visa processing. Dubai and Abu Dhabi job placements, document attestation, and Golden Visa eligibility assessment.'),

((SELECT id FROM countries WHERE code='ARE'), 'work', 'UAE Golden Visa', 'golden-visa',
'The UAE Golden Visa offers 10-year residency for investors, entrepreneurs, specialized talents, researchers, and outstanding students. No sponsor needed.',
'["Investor: property worth AED 2M+", "Entrepreneur: approved startup", "Specialized talent: exceptional skills in culture, art, sports, digital technology, etc.", "Scientist/Researcher: significant contribution", "Outstanding student: top university graduate"]',
'["Passport", "Proof of category eligibility", "Financial documents", "Recommendation letters", "Medical test", "Emirates ID"]',
'["Passport", "Photos", "Eligibility proof", "Financial statements", "Recommendation letter", "Degree/certificates", "Medical fitness", "Emirates ID form"]',
'2-4 weeks', '10 years', 150000, 4000, 'AED', 97.8, false, true, false, '10-year renewable residency',
'["Investment", "Technology", "Science", "Culture", "Sports", "Entrepreneurship", "Education"]',
'[]', true, 2,
'UAE Golden Visa | 10-Year Residency | Siddhivinayak Overseas',
'UAE Golden Visa application for investors, entrepreneurs, and specialized talents. 10-year residency, no sponsor required, family inclusion.'),

((SELECT id FROM countries WHERE code='ARE'), 'study', 'Student Residence Visa', 'student-residence-visa',
'The UAE student residence visa is sponsored by the educational institution. Valid for the duration of studies with part-time work options in some cases.',
'["Enrollment in UAE university/college", "Medical fitness test", "Valid passport", "Financial support proof", "Parental consent (if under 18)"]',
'["Passport", "Admission letter", "Medical test", "Photos", "Financial proof", "Parental consent (if minor)", "Insurance"]',
'["Passport", "Photos", "Admission letter", "Medical fitness", "Financial documents", "Parental consent", "Health insurance", "Emirates ID form"]',
'2-4 weeks', '1 year, renewable', 70000, 2000, 'AED', 94.5, false, false, false, 'Employment visa after graduation',
'["Business", "Engineering", "IT", "Hospitality", "Aviation", "Design", "Media"]',
'["UAE University", "American University of Dubai", "University of Wollongong Dubai", "Heriot-Watt Dubai", "Manipal Academy Dubai"]',
false, 3,
'UAE Student Visa | Study in Dubai | Siddhivinayak Overseas',
'UAE student residence visa. Dubai university admissions, medical tests, and part-time work options for international students.');

-- FAQ data for Japan (sample)
INSERT INTO country_faqs (country_id, question, answer, category, sort_order) VALUES
((SELECT id FROM countries WHERE code='JPN'), 'Do I need to know Japanese for the Specified Skilled Worker visa?', 'Yes, you need to pass the Japanese Language Proficiency Test (JLPT) at N4 level or pass the Japan Foundation Test for Basic Japanese. Some sectors may require N3 level for advancement.', 'language', 1),
((SELECT id FROM countries WHERE code='JPN'), 'Can I bring my family on the SSW visa?', 'Yes, after completing 1 year on the SSW visa and demonstrating stable income, you can apply to bring your spouse and children. Additional financial requirements apply.', 'family', 2),
((SELECT id FROM countries WHERE code='JPN'), 'What is the Certificate of Eligibility (COE)?', 'The COE is a document issued by Japanese Immigration confirming you meet landing conditions. Your employer or school applies for this before you apply for the visa at the embassy.', 'process', 3),
((SELECT id FROM countries WHERE code='JPN'), 'How much can I earn in Japan on a work visa?', 'Salaries vary by sector and region. On average, SSW workers earn ¥180,000-250,000/month. IT and engineering roles can pay ¥300,000-500,000+. Overtime pay is mandatory by law.', 'salary', 4);

-- FAQ data for Australia (sample)
INSERT INTO country_faqs (country_id, question, answer, category, sort_order) VALUES
((SELECT id FROM countries WHERE code='AUS'), 'What is the points test for Australian PR?', 'The points test awards points for age (max 30 points), English proficiency (max 20 points), skilled employment (max 20 points), educational qualifications (max 20 points), and other factors. You need 65 points minimum to submit an EOI.', 'pr', 1),
((SELECT id FROM countries WHERE code='AUS'), 'Can I work while studying in Australia?', 'Yes, student visa holders can work up to 48 hours per fortnight during term and unlimited hours during breaks. Masters by research and PhD students have unlimited work rights.', 'work_rights', 2),
((SELECT id FROM countries WHERE code='AUS'), 'What is the difference between 189, 190, and 491 visas?', '189 is independent PR (no state sponsor), 190 is state-nominated PR (extra 5 points), and 491 is provisional regional visa (15 extra points, pathway to 191 PR after 3 years in regional area).', 'visa_types', 3);
